import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { AccountingEmployee } from '../components/models/accounting-employee';
@Injectable({
  providedIn: 'root'
})
export class AccountingEmployeeService {

  private employees: AccountingEmployee[] = [
    {'id': 931,
  'firstName': 'Christopher',
  'lastName': 'Fisher',
  'email': 'rebecca49@yahoo.com',
  'position': 'Social worker',
  'startDate': '2021-12-09',
  'salary': 49234.9,
  'performanceReview': 'Poor',
  'annualLeave': 17},
 {'id': 733,
  'firstName': 'Crystal',
  'lastName': 'Barrett',
  'email': 'rebeccawyatt@hotmail.com',
  'position': 'Sport and exercise psychologist',
  'startDate': '2021-05-03',
  'salary': 66253.76,
  'performanceReview': 'Below Average',
  'annualLeave': 20},
 {'id': 1,
  'firstName': 'Heather',
  'lastName': 'Arnold',
  'email': 'joyce96@gmail.com',
  'position': 'Equities trader',
  'startDate': '2024-04-18',
  'salary': 69092.06,
  'performanceReview': 'Good',
  'annualLeave': 10},
 {'id': 20,
  'firstName': 'Russell',
  'lastName': 'Neal',
  'email': 'smithjessica@gmail.com',
  'position': 'Best boy',
  'startDate': '2020-06-23',
  'salary': 78946.08,
  'performanceReview': 'Good',
  'annualLeave': 13},
 {'id': 807,
  'firstName': 'Anthony',
  'lastName': 'Walsh',
  'email': 'dawn02@hotmail.com',
  'position': 'Aid worker',
  'startDate': '2020-07-20',
  'salary': 64023.23,
  'performanceReview': 'Poor',
  'annualLeave': 22},
 {'id': 32,
  'firstName': 'Victoria',
  'lastName': 'Murphy',
  'email': 'michelle83@yahoo.com',
  'position': 'Structural engineer',
  'startDate': '2019-07-20',
  'salary': 75802.39,
  'performanceReview': 'Average',
  'annualLeave': 25},
 {'id': 665,
  'firstName': 'Katherine',
  'lastName': 'Walker',
  'email': 'woodmaria@roman.com',
  'position': 'Lexicographer',
  'startDate': '2023-07-14',
  'salary': 97389.04,
  'performanceReview': 'Below Average',
  'annualLeave': 19},
 {'id': 709,
  'firstName': 'Alison',
  'lastName': 'Buchanan',
  'email': 'mossstephen@yahoo.com',
  'position': 'Careers adviser',
  'startDate': '2023-12-10',
  'salary': 70894.3,
  'performanceReview': 'Average',
  'annualLeave': 13},
 {'id': 158,
  'firstName': 'Jacqueline',
  'lastName': 'Serrano',
  'email': 'maryroberson@carter.net',
  'position': 'Statistician',
  'startDate': '2023-05-25',
  'salary': 31125.63,
  'performanceReview': 'Poor',
  'annualLeave': 18},
 {'id': 95,
  'firstName': 'Christopher',
  'lastName': 'Flores',
  'email': 'holdertara@myers.com',
  'position': 'Conservation officer, nature',
  'startDate': '2020-12-20',
  'salary': 96613.54,
  'performanceReview': 'Good',
  'annualLeave': 12},
 {'id': 494,
  'firstName': 'Andrea',
  'lastName': 'Copeland',
  'email': 'clayton98@gmail.com',
  'position': 'Fitness centre manager',
  'startDate': '2024-05-10',
  'salary': 59378.04,
  'performanceReview': 'Excellent',
  'annualLeave': 7},
 {'id': 156,
  'firstName': 'David',
  'lastName': 'Welch',
  'email': 'juliedaniels@wells.com',
  'position': 'Product designer',
  'startDate': '2023-05-05',
  'salary': 88551.24,
  'performanceReview': 'Poor',
  'annualLeave': 27},
 {'id': 772,
  'firstName': 'John',
  'lastName': 'Johnson',
  'email': 'vgordon@moreno-long.info',
  'position': 'Teacher, special educational needs',
  'startDate': '2021-08-21',
  'salary': 89494.82,
  'performanceReview': 'Good',
  'annualLeave': 27},
 {'id': 945,
  'firstName': 'Nathaniel',
  'lastName': 'Williams',
  'email': 'kallen@yahoo.com',
  'position': 'Field trials officer',
  'startDate': '2022-11-18',
  'salary': 49523.92,
  'performanceReview': 'Excellent',
  'annualLeave': 20},
 {'id': 447,
  'firstName': 'Kendra',
  'lastName': 'Bailey',
  'email': 'rmelton@robbins.info',
  'position': 'IT sales professional',
  'startDate': '2022-08-11',
  'salary': 89896.39,
  'performanceReview': 'Excellent',
  'annualLeave': 26},
 {'id': 943,
  'firstName': 'Amanda',
  'lastName': 'Horn',
  'email': 'lewislisa@gmail.com',
  'position': 'Nature conservation officer',
  'startDate': '2020-07-11',
  'salary': 72534.9,
  'performanceReview': 'Poor',
  'annualLeave': 18},
 {'id': 456,
  'firstName': 'Paula',
  'lastName': 'Flores',
  'email': 'elizabeth65@jones.org',
  'position': 'TEFL teacher',
  'startDate': '2021-08-28',
  'salary': 97520.48,
  'performanceReview': 'Excellent',
  'annualLeave': 12},
 {'id': 881,
  'firstName': 'Andrew',
  'lastName': 'Blair',
  'email': 'hardingkristy@simmons.net',
  'position': 'Licensed conveyancer',
  'startDate': '2019-08-13',
  'salary': 54827.47,
  'performanceReview': 'Below Average',
  'annualLeave': 5},
 {'id': 505,
  'firstName': 'Devin',
  'lastName': 'Robinson',
  'email': 'monica50@lopez.com',
  'position': 'Horticultural therapist',
  'startDate': '2021-08-17',
  'salary': 33571.06,
  'performanceReview': 'Poor',
  'annualLeave': 12},
 {'id': 608,
  'firstName': 'Anna',
  'lastName': 'Rogers',
  'email': 'jasonsmith@yahoo.com',
  'position': 'Tour manager',
  'startDate': '2021-02-10',
  'salary': 66565.29,
  'performanceReview': 'Poor',
  'annualLeave': 16},
 {'id': 343,
  'firstName': 'John',
  'lastName': 'Long',
  'email': 'williamlewis@lewis.biz',
  'position': 'Quantity surveyor',
  'startDate': '2021-01-18',
  'salary': 94108.0,
  'performanceReview': 'Good',
  'annualLeave': 5},
 {'id': 884,
  'firstName': 'Monica',
  'lastName': 'Wilson',
  'email': 'lkirby@yahoo.com',
  'position': 'Professor Emeritus',
  'startDate': '2019-10-04',
  'salary': 33219.95,
  'performanceReview': 'Average',
  'annualLeave': 7},
 {'id': 5,
  'firstName': 'Michael',
  'lastName': 'Sawyer',
  'email': 'cassandra74@hotmail.com',
  'position': 'Geochemist',
  'startDate': '2020-06-06',
  'salary': 67438.36,
  'performanceReview': 'Excellent',
  'annualLeave': 22},
 {'id': 571,
  'firstName': 'Kelly',
  'lastName': 'Cook',
  'email': 'bthompson@gmail.com',
  'position': 'Clinical psychologist',
  'startDate': '2019-12-10',
  'salary': 50773.76,
  'performanceReview': 'Average',
  'annualLeave': 9},
 {'id': 478,
  'firstName': 'Christina',
  'lastName': 'Obrien',
  'email': 'msantiago@hotmail.com',
  'position': 'Insurance underwriter',
  'startDate': '2020-07-13',
  'salary': 81385.09,
  'performanceReview': 'Excellent',
  'annualLeave': 5},
 {'id': 850,
  'firstName': 'Daniel',
  'lastName': 'Townsend',
  'email': 'qfletcher@hernandez.com',
  'position': 'Clinical embryologist',
  'startDate': '2022-09-29',
  'salary': 56551.11,
  'performanceReview': 'Average',
  'annualLeave': 19},
 {'id': 792,
  'firstName': 'David',
  'lastName': 'Martinez',
  'email': 'sanchezpaul@hotmail.com',
  'position': 'Soil scientist',
  'startDate': '2023-09-15',
  'salary': 86349.84,
  'performanceReview': 'Poor',
  'annualLeave': 6},
 {'id': 700,
  'firstName': 'Dustin',
  'lastName': 'Williams',
  'email': 'newtontammy@walker-dominguez.com',
  'position': 'Broadcast engineer',
  'startDate': '2020-06-16',
  'salary': 97048.52,
  'performanceReview': 'Good',
  'annualLeave': 25},
 {'id': 780,
  'firstName': 'Albert',
  'lastName': 'Martinez',
  'email': 'reevessarah@gibson-lee.biz',
  'position': 'Interpreter',
  'startDate': '2022-07-03',
  'salary': 70686.96,
  'performanceReview': 'Poor',
  'annualLeave': 17},
 {'id': 318,
  'firstName': 'Michelle',
  'lastName': 'Hughes',
  'email': 'colonnicole@hotmail.com',
  'position': 'Insurance account manager',
  'startDate': '2020-03-13',
  'salary': 42865.12,
  'performanceReview': 'Average',
  'annualLeave': 22}
  ];

  constructor() { }

  getEmployees(): Observable<AccountingEmployee[]> {
    return of(this.employees);
  }

  addEmployee(employee: AccountingEmployee): Observable<AccountingEmployee[]> {
    if (employee.id == null) { 
      employee.id = this.getNextId(); 
    }
    this.employees.push(employee);
    return of(this.employees);
  }

  deleteEmployee(id: number): Observable<any> {
    this.employees = this.employees.filter(employee => employee.id !== id);
    return of({ success: true });
  }

  private getNextId(): number {
    return this.employees.reduce((acc, cur) => Math.max(acc, cur.id), 0) + 1;
  }
}